image: maven:latest
variables:
  SONAR_TOKEN: "980102eb7bb795dd9ea4f2142945b3a0eaf35365"
  SONAR_HOST_URL: "https://sonarcloud.io"
  GIT_DEPTH: 0

sonarcloud-backend-job-service:
  stage: backend
  script:
    - cd "${CI_PROJECT_DIR}/backend/job-service"
    - mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=jobs-service -Dsonar.login=980102eb7bb795dd9ea4f2142945b3a0eaf35365
  allow_failure: true
  only:
    - merge_requests
    - main
