image: maven:latest
variables:
  SONAR_TOKEN: "45a2e5e168db0e2d2c9ff52c4f77691bd24e4345"
  SONAR_HOST_URL: "https://sonarcloud.io"
  GIT_DEPTH: 0

sonarcloud-backend-skill-service:
  stage: sonar-skill
  script:
    - cd "${CI_PROJECT_DIR}/backend/skills-service"
    - mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=skills -Dsonar.login=45a2e5e168db0e2d2c9ff52c4f77691bd24e4345
  allow_failure: true
  only:
    - merge_requests
    - main