<<<<<<< HEAD
include:
  - "/frontend/.gitlab-ci.yml"
  - "/backend/appliedjobs-service/.gitlab-ci.yml"
  - "/backend/savedjobs-service/.gitlab-ci.yml"
  - "/backend/location-service/.gitlab-ci.yml"
  - "/backend/skills-service/.gitlab-ci.yml"
  - "/backend/job-service/.gitlab-ci.yml"
  - "/backend/routes-service/.gitlab-ci.yml"

stages:
  - backend
  - sonarcloud-check-frontend
  - netlify
=======
include : 
  # - "/frontend/.gitlab-ci.yml"
  - "/backend/.gitlab-ci.yml"
 
>>>>>>> backend
