image: 
   name: amazon/aws-cli
   entrypoint: [""]   
services:
    - name: docker:20-dind
      command: ["--tls=false"]

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay
  DOCKER_TLS_CERTDIR: ""

stages:
    - Build image and Push to Docker Hub
    - deploy
docker build and push:
    stage: Build image and Push to Docker Hub
    only:
        - deployment

    before_script:
        - amazon-linux-extras install docker
        - aws --version
        - docker --version
        - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
    script:
        - cd backend
        - cd appliedjobs-service
        - docker build . -t applied388:1
        - docker tag applied388:1 "$REGISTRY_USER"/applied_bc388:1
        - docker push "$REGISTRY_USER"/applied_bc388:1
        - cd ..
        - cd cloud-gateway
        - docker build . -t cloud388:1
        - docker tag cloud388:1 "$REGISTRY_USER"/cloud_bc388:1
        - docker push "$REGISTRY_USER"/cloud_bc388:1 
        - cd .. 
        - cd job-service
        - docker build . -t job388:1
        - docker tag job388:1 "$REGISTRY_USER"/job_bc388:1
        - docker push "$REGISTRY_USER"/job_bc388:1 
        - cd ..
        - cd location-service
        - docker build . -t location388:1
        - docker tag location388:1 "$REGISTRY_USER"/location_bc388:1
        - docker push "$REGISTRY_USER"/location_bc388:1
        - cd ..
        - cd routes-service
        - docker build . -t routes388:1
        - docker tag routes388:1 "$REGISTRY_USER"/routes_bc388:1
        - docker push "$REGISTRY_USER"/routes_bc388:1
        - cd ..
        - cd savedjobs-service
        - docker build . -t savedjobs388:1
        - docker tag savedjobs388:1 "$REGISTRY_USER"/savedjobs_bc388:1
        - docker push "$REGISTRY_USER"/savedjobs_bc388:1
        - cd ..
        - cd service-registry
<<<<<<< HEAD
        - docker build . -t service388:1
        - docker tag service388:1 "$REGISTRY_USER"/service_bc388:1
        - docker push "$REGISTRY_USER"/service_bc388:1
=======
        - docker build . -t service3:1
        - docker tag service3:1 "$REGISTRY_USER"/service_bc3:1
        - docker push "$REGISTRY_USER"/service_bc3:1
>>>>>>> backend
        - cd ..
        - cd skills-service
        - docker build . -t skills388:1
        - docker tag skills388:1 "$REGISTRY_USER"/skills_bc388:1
        - docker push "$REGISTRY_USER"/skills_bc388:1
    environment:
       name: staging
       url:
deploy:
  stage: deploy  
  image: kroniak/ssh-client
   
  before_script:
      - mkdir ~/.ssh
      - echo -e "$KEY_PAIR" > ~/.ssh/id_rsa
      - chmod 600 ~/.ssh/id_rsa
      - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  script: 
    - ssh ubuntu@3.144.240.106 "sudo docker-compose up -d "   
    - exit  
  only:
    - deployment
  environment:
      name: production
      url: 
