image: 
   name: amazon/aws-cli
   entrypoint: [""]   
services:
    - name: docker:20-dind
      command: ["--tls=false"]

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay
  DOCKER_TLS_CERTDIR: ""

stages:
    - Build image and Push to Docker Hub
    - deploy
docker build and push:
    stage: Build image and Push to Docker Hub
    only:
        - deployment

    before_script:
        - amazon-linux-extras install docker
        - aws --version
        - docker --version
        - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
    script:
        - cd backend
        - cd appliedjobs-service
        - docker build . -t applied1:1
        - docker tag applied1:1 "$REGISTRY_USER"/applied_bc38:1
        - docker push "$REGISTRY_USER"/applied_bc38:1
        - cd ..
        - cd cloud-gateway
        - docker build . -t cloud1:1
        - docker tag cloud1:1 "$REGISTRY_USER"/cloud_bc38:1
        - docker push "$REGISTRY_USER"/cloud_bc38:1 
        - cd .. 
        - cd job-service
        - docker build . -t job1:1
        - docker tag job1:1 "$REGISTRY_USER"/job_bc38:1
        - docker push "$REGISTRY_USER"/job_bc38:1 
        - cd ..
        - cd location-service
        - docker build . -t location1:1
        - docker tag location1:1 "$REGISTRY_USER"/location_bc38:1
        - docker push "$REGISTRY_USER"/location_bc38:1
        - cd ..
        - cd routes-service
        - docker build . -t routes1:1
        - docker tag routes1:1 "$REGISTRY_USER"/routes_bc38:1
        - docker push "$REGISTRY_USER"/routes_bc38:1
        - cd ..
        - cd savedjobs-service
        - docker build . -t savedjobs1:1
        - docker tag savedjobs1:1 "$REGISTRY_USER"/savedjobs_bc38:1
        - docker push "$REGISTRY_USER"/savedjobs_bc38:1
        - cd ..
        - cd service-registry
        - docker build . -t service1:1
        - docker tag service1:1 "$REGISTRY_USER"/service_bc38:1
        - docker push "$REGISTRY_USER"/service_bc38:1
        - cd ..
        - cd skills-service
        - docker build . -t skills1:1
        - docker tag skills1:1 "$REGISTRY_USER"/skills_bc38:1
        - docker push "$REGISTRY_USER"/skills_bc38:1
    environment:
       name: staging
       url:
deploy:
  stage: deploy  
  image: kroniak/ssh-client
   
  before_script:
      - mkdir ~/.ssh
      - echo -e "$KEY_PAIR" > ~/.ssh/id_rsa
      - chmod 600 ~/.ssh/id_rsa
      - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  script: 
    - ssh ubuntu@3.144.240.106 "sudo docker-compose up -d "   
    - exit  
  only:
    - deployment
  environment:
      name: production
      url: 
