version: '3.1'

services:

  service-registry :
    image: ghcr.io/malyadr/servicejenkins:latest
    container_name: service
    restart: always
    ports:
     - 8761:8761

  cloud-gateway: 
    image: ghcr.io/malyadr/cloudjenkins:latest
    container_name: cloudgateway 
    restart: always
    ports:
     - 9191:9191

  job-service :
    image: ghcr.io/malyadr/jobjenkins:latest
    container_name: job-service
    restart: always
    ports:
     - 9001:9001 
    depends_on:
       - cloud-gateway 
  
  location-service:
    image: ghcr.io/malyadr/locationjenkins:latest
    container_name: location-service
    restart: always
    ports:
     - 9006:9006
    depends_on:
       - cloud-gateway 

  routes-service:
    image: ghcr.io/malyadr/routesjenkins:latest
    container_name: routes-service
    restart: always
    ports:
     - 9004:9004
    depends_on:
       - cloud-gateway 

  savedjobs-service:
    image: ghcr.io/malyadr/savedjobsjenkins:latest
    container_name: saved-jobs
    restart: always
    ports:
     - 9002:9002
    depends_on:
       - cloud-gateway 
  appliedjobs-services:
    image: ghcr.io/malyadr/applyjenkins:latest
    container_name: applied-jobs
    restart: always
    ports:
     - 9003:9003
    depends_on:
       - cloud-gateway 
  skills-services:
    image: ghcr.io/malyadr/skillsjenkins:latest
    container_name: skills-jobs
    restart: always
    ports:
     - 9005:9005
    depends_on:
       - cloud-gateway      
     
       

