START TRANSACTION;
USE `green_commute_db`;
INSERT INTO `green_commute_db`.`jobs` (`id`, `description`, `company_name`, `role`, `image`, `distance`, `time`, `location_id`) VALUES (1, 'Open Text is seeking a talented, personable interaction designer who can assist the User Experience Design team by working with other designers and development teams on a variety of projects. The OpenText User Experience Design group is a distributed multi-disciplinary team of professionals that are responsible for enhancing the UX of the company’s collective product suites worldwide.',  'HP', 'Backend Developer', 'hp', '0-10kms',  '1hr 36 mins ago', 1);
INSERT INTO `green_commute_db`.`jobs` (`id`, `description`, `company_name`, `role`, `image`, `distance`, `time`, `location_id`) VALUES (2, 'Open Text is seeking a talented, personable interaction designer who can assist the User Experience Design team by working with other designers and development teams on a variety of projects. The OpenText User Experience Design group is a distributed multi-disciplinary team of professionals that are responsible for enhancing the UX of the company’s collective product suites worldwide.',  'Instagram', 'User Experience Designer', 'instagram', '0-10kms',  '45 min ago', 1);
INSERT INTO `green_commute_db`.`jobs` (`id`, `description`, `company_name`, `role`, `image`, `distance`, `time`, `location_id`) VALUES (3, 'Open Text is seeking a talented, personable interaction designer who can assist the User Experience Design team by working with other designers and development teams on a variety of projects. The OpenText User Experience Design group is a distributed multi-disciplinary team of professionals that are responsible for enhancing the UX of the company’s collective product suites worldwide.',  'BMW', 'User Experience Designer', 'bmw', '11-20kms',  '3 days ago', 1);
INSERT INTO `green_commute_db`.`jobs` (`id`, `description`, `company_name`, `role`, `image`, `distance`, `time`, `location_id`) VALUES (4, 'Open Text is seeking a talented, personable interaction designer who can assist the User Experience Design team by working with other designers and development teams on a variety of projects. The OpenText User Experience Design group is a distributed multi-disciplinary team of professionals that are responsible for enhancing the UX of the company’s collective product suites worldwide.',  'Myntra', 'User Experience Designer', 'myntra', '21-30kms',  '4 days ago', 1);
INSERT INTO `green_commute_db`.`jobs` (`id`, `description`, `company_name`, `role`, `image`, `distance`, `time`, `location_id`) VALUES (5, 'Open Text is seeking a talented, personable interaction designer who can assist the User Experience Design team by working with other designers and development teams on a variety of projects. The OpenText User Experience Design group is a distributed multi-disciplinary team of professionals that are responsible for enhancing the UX of the company’s collective product suites worldwide.',  'Twitter', 'User Experience Designer', 'twitter', '31-40kms',  '1 week ago', 3);
INSERT INTO `green_commute_db`.`jobs` (`id`, `description`, `company_name`, `role`, `image`, `distance`, `time`, `location_id`) VALUES (6, 'Open Text is seeking a talented, personable interaction designer who can assist the User Experience Design team by working with other designers and development teams on a variety of projects. The OpenText User Experience Design group is a distributed multi-disciplinary team of professionals that are responsible for enhancing the UX of the company’s collective product suites worldwide.',  'Wipro', 'User Experience Designer', 'wipro', '21-30kms',  '10 days ago', 3);

COMMIT;
