image: maven:latest
variables:
  SONAR_TOKEN: "810768cb86b8ec70854803ae2c7320be959d7e97"
  SONAR_HOST_URL: "https://sonarcloud.io"
  GIT_DEPTH: 0

sonarcloud-backend-appliedjobs-service:
  stage: backend
  script:
    - cd "${CI_PROJECT_DIR}/backend/appliedjobs-service"
    - mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=applied_jobs -Dsonar.login=810768cb86b8ec70854803ae2c7320be959d7e97
  allow_failure: true
  only:
    - merge_requests
    - main
