server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**
        - id: SKILL-SERVICE
          uri: lb://SKILL-SERVICE
          predicates:
            - Path=/skill/**
        - id: GREEN-COMMUTE-ROUTES-SERVICE
          uri: lb://GREEN-COMMUTE-ROUTES-SERVICE
          predicates:
            - Path=/routes/**
        - id: JOB-SERVICE
          uri: lb://JOB-SERVICE
          predicates:
            - Path=/jobs/**
        - id: LOCATION-SERVICE
          uri: lb://LOCATION-SERVICE
          predicates:
            - Path=/locations/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost