server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: SKILLS-SERVICE
          uri: lb://SKILLS-SERVICE
          predicates:
            - Path=/skills/**
        - id: ROUTES-SERVICE
          uri: lb://ROUTES-SERVICE
          predicates:
            - Path=/routes/**
        - id: JOBS-SERVICE
          uri: lb://JOBS-SERVICE
          predicates:
            - Path=/jobs/**
        - id: LOCATION-SERVICE
          uri: lb://LOCATION-SERVICE
          predicates:
            - Path=/locations/**
        - id: APPLIED-JOBS-SERVICE
          uri: lb://APPLIED-JOBS-SERVICE
          predicates:
<<<<<<< HEAD
            - Path=/appliedJobs/**
        - id: SAVED-JOBS-SERVICE
          uri: lb://SAVED-JOBS-SERVICE
          predicates:
            - Path=/savedJobs/**
=======
              - Path=/appliedJobs/**
        - id: SAVED-JOBS-SERVICE
          uri: lb://SAVED-JOBS-SERVICE
          predicates:
              - Path=/savedJobs/**
>>>>>>> backend

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://3.144.240.106:8761/eureka/
    instance:
      hostname: 3.144.240.106
