image: maven:latest
variables:
  SONAR_TOKEN: "96c288a9d2f4b2d08c0d38435c845edbe7d77c51"
  SONAR_HOST_URL: "https://sonarcloud.io"
  GIT_DEPTH: 0

sonarcloud-backend-savedjobs-service:
  stage: backend
  script:
    - cd "${CI_PROJECT_DIR}/backend/savedjobs-service"
    - mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=saved_jobs -Dsonar.login=96c288a9d2f4b2d08c0d38435c845edbe7d77c51
  allow_failure: true
  only:
    - merge_requests
    - main
