server:
  port: 9003

spring:
  application:
    name: APPLIED-JOBS-SERVICE
  datasource:
    url: jdbc:mysql://18.191.37.77:3306/green_commute_db?useLegacyDatetimeCode=false&serverTimezone=Australia/Sydney&useSSL=false
    username: root
    password: Data@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
  cloud:
    config:
      enabled: false
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://3.144.240.106:8761/eureka/
  instance:
    hostname: 3.144.240.106