server:
  port: 9001


spring:
  application:
    name: JOBS-SERVICE
  datasource:
    url: jdbc:mysql://18.191.37.77:3306/green_commute_db?useSSL=false&serverTimezone=UTC
    username: root
    password: Data@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
  cloud:
    config:
      enabled: false

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://3.144.240.106:8761/eureka/
    instance:
      hostname: 3.144.240.106